### PR TITLE
Make history file optional

### LINKED ISSUE #7: Graql shell crashes if a user doesn't have a home directory
_This issue was originally posted by @kasper-piskorski  on 2018-01-26 12:11_.

NB: not sure if we should fix that, just logging it here so that we know 
```
 java.io.IOException: No such file or directory at java.io.UnixFileSystem.createFileExclusively(Native Method) at java.io.File.createNewFile(File.java:1012) at ai.grakn.graql.GraqlShell.setupHistory(GraqlShell.java:474) at ai.grakn.graql.GraqlShell.executeRepl(GraqlShell.java:394) at ai.grakn.graql.GraqlShell.start(GraqlShell.java:370) at ai.grakn.graql.GraqlShell.runShell(GraqlShell.java:266) at ai.grakn.graql.GraqlShell.runShell(GraqlShell.java:170) at ai.grakn.graql.GraqlShell.main(GraqlShell.java:165) at ai.grakn.dist.DistGraql.run(DistGraql.java:52) at ai.grakn.dist.DistGraql.main(DistGraql.java:44) 
```
 I believe the cause is this: 
```
 private static final String HISTORY_FILENAME = StandardSystemProperty.USER_HOME.value() + "/.graql-history"; 
```
 If a user doesn't have a home directory it throws an exception on file creation.

### PR DESCRIPTION
**Pull request by vmax**
## What is the goal of this PR?

Fix #7
Previously, Grakn Console would crash in case history file could not be created (possible reasons are user's home directory being non-present or mounted read-only)

## What are the changes implemented in this PR?

- Bump `@graknlabs_protocol` version
- Make an adapter class which allows to `.flush()` history object regardless of whether it's backed by `FileHistory` or `MemoryHistory`
- Resort to using in-memory history in case history file could not be created

### CODE REVIEW

File: ConsoleSession.java [hunk 1]
```diff
@@ -280,7 +288,7 @@ public final void close() {
         session.close();
         client.close();
         try {
-            historyFile.flush();
+            history.flush();
```
Comment (marco-scoppetta) [inline ConsoleSession.java]: Given that we only flush once I think you can change the field `history` to be `History` rather than `PersistentHistory` and then in this `try-catch` you can just check `if(history instanceof PeristentHistory) { history.flush(); }` , so that we don't need to create a fake empty class.

File: ConsoleSession.java [hunk 2]
```diff
@@ -97,10 +99,16 @@
         this.consoleReader.setPrompt(ANSI_PURPLE + session.keyspace().name() + ANSI_RESET + "> ");
         this.printErr = printErr;
 
-        File file = new File(HISTORY_FILE);
-        file.createNewFile();
-        this.historyFile = new FileHistory(file);
-        this.consoleReader.setHistory(this.historyFile);
+        PersistentHistory history;
+        try {
+            File file = new File(HISTORY_FILE);
```
Comment (marco-scoppetta) [inline ConsoleSession.java]: Here you can maybe use `File.exists()` rather then creating a `history = new FlushableMemoryHistory();` in the `catch` block

Comment (marco-scoppetta) [reply ConsoleSession.java]: Or you can also keep the catch, but I think it's important that we log with a warning the fact that we are falling back to an in-memory history, so maybe just add in the catch:
```
LOG.warn("An in-memory history will be used due to exception raised while trying to access history file: ", e.getMessage());
history = new FlushableMemoryHistory();
```

Comment (vmax) [reply ConsoleSession.java]: @marco-scoppetta I think we actually want to fallback on _any_ case on not being able to create/open a file. How could I utilize `File.exists` if creating a new file triggers `IOException`?

Comment (marco-scoppetta) [reply ConsoleSession.java]: @vmax https://github.com/graknlabs/console/pull/16#discussion_r344146485
